# Generated by Django 4.2.20 on 2025-04-05 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='house',
            fields=[
                ('description', models.TextField(blank=True, null=True)),
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=200)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_type', models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Studio Apartment', 'Studioapartment')], max_length=50)),
                ('square_feet', models.IntegerField()),
                ('number_of_bedrooms', models.IntegerField()),
                ('number_of_bathrooms', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('Available_from', models.DateField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
